/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SkinsIndexRouteImport } from './routes/skins/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ModpacksIndexRouteImport } from './routes/modpacks/index'
import { Route as BrowseIndexRouteImport } from './routes/browse/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkinsIndexRoute = SkinsIndexRouteImport.update({
  id: '/skins/',
  path: '/skins/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModpacksIndexRoute = ModpacksIndexRouteImport.update({
  id: '/modpacks/',
  path: '/modpacks/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseIndexRoute = BrowseIndexRouteImport.update({
  id: '/browse/',
  path: '/browse/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account/': typeof AccountIndexRoute
  '/browse/': typeof BrowseIndexRoute
  '/modpacks/': typeof ModpacksIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/skins/': typeof SkinsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountIndexRoute
  '/browse': typeof BrowseIndexRoute
  '/modpacks': typeof ModpacksIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/skins': typeof SkinsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account/': typeof AccountIndexRoute
  '/browse/': typeof BrowseIndexRoute
  '/modpacks/': typeof ModpacksIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/skins/': typeof SkinsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account/'
    | '/browse/'
    | '/modpacks/'
    | '/settings/'
    | '/skins/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/account' | '/browse' | '/modpacks' | '/settings' | '/skins'
  id:
    | '__root__'
    | '/'
    | '/account/'
    | '/browse/'
    | '/modpacks/'
    | '/settings/'
    | '/skins/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountIndexRoute: typeof AccountIndexRoute
  BrowseIndexRoute: typeof BrowseIndexRoute
  ModpacksIndexRoute: typeof ModpacksIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SkinsIndexRoute: typeof SkinsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skins/': {
      id: '/skins/'
      path: '/skins'
      fullPath: '/skins/'
      preLoaderRoute: typeof SkinsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modpacks/': {
      id: '/modpacks/'
      path: '/modpacks'
      fullPath: '/modpacks/'
      preLoaderRoute: typeof ModpacksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse/': {
      id: '/browse/'
      path: '/browse'
      fullPath: '/browse/'
      preLoaderRoute: typeof BrowseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountIndexRoute: AccountIndexRoute,
  BrowseIndexRoute: BrowseIndexRoute,
  ModpacksIndexRoute: ModpacksIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SkinsIndexRoute: SkinsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
